#!/usr/bin/env python

import signal, sys

def sig_handler(s, f):
      print("Got SIGTERM")
      sys.exit(0)

signal.signal(signal.SIGTERM, sig_handler)

print("I'm a module!")

x = 0
while True:
      x = (x + 1)%50000000
      if x == 0:
         print("Module: ping")

